version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8007"
    volumes:
      - .:/app
    ports:
      - "8007:8007"
    env_file:
      - .env
    restart: unless-stopped
