version: '3.8'

services:
  web:
    build: .
    command: poetry run python manage.py runserver ${HOST}:${PORT}
    volumes:
      - .:/app
    ports:
      - "${EXTERNAL_PORT}:${PORT}"
    env_file:
      - .env
    restart: unless-stopped
